image: alpine/edge
packages:
  - go
  - linux-pam-dev
  - scdoc
sources:
  - https://github.com/emersion/maddy
tasks:
  - build: |
      cd maddy
      go build ./...
  - test: |
      cd maddy
      go test -race ./...
  - build-man-pages: |
      cd maddy
      scdoc <maddy.1.scd >/dev/null
      scdoc <maddy.conf.5.scd >/dev/null
