//go:build integration

/*
Maddy Mail Server - Composable all-in-one email server.
Copyright © 2019-2020 Max Mazurov <fox.cpp@disroot.org>, Maddy Mail Server contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

package tests_test

import (
	"testing"

	"github.com/foxcpp/maddy/tests"
)

func TestConfigCycle(tt *testing.T) {
	tt.Parallel()

	t := tests.NewT(tt)
	t.DNS(nil)
	t.Config(`
		hostname mx.maddy.test

		msgpipeline local_routing {
			destination maddy.test {
				deliver_to dummy
			}
			default_destination {
				deliver_to &outbound_queue
			}
		}

		target.queue outbound_queue {
			target dummy
			autogenerated_msg_domain maddy.test
			bounce {
				deliver_to &local_routing
			}
		}

		smtp tcp://127.0.0.1:1443 {
			tls off

			deliver_to &local_routing
		}
    `)
	t.Run(1)

	t.Close()
}
